# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NeulandHit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10NeulandHit.proto\x12\tProtoHits\"\xf0\x01\n\nNeulandHit\x12\x0c\n\x04TDCL\x18\x01 \x01(\x01\x12\x0c\n\x04TDCR\x18\x02 \x01(\x01\x12\x0c\n\x04time\x18\x03 \x01(\x01\x12\x0c\n\x04QDCL\x18\x04 \x01(\x01\x12\x0c\n\x04QDCR\x18\x05 \x01(\x01\x12\x0e\n\x06\x65nergy\x18\x06 \x01(\x01\x12\x30\n\x08position\x18\x07 \x01(\x0b\x32\x1e.ProtoHits.NeulandHit.Vector3D\x12-\n\x05pixel\x18\x08 \x01(\x0b\x32\x1e.ProtoHits.NeulandHit.Vector3D\x1a+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"1\n\x0bNeulandHits\x12\"\n\x03hit\x18\x01 \x03(\x0b\x32\x15.ProtoHits.NeulandHitb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NeulandHit_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEULANDHIT._serialized_start=32
  _NEULANDHIT._serialized_end=272
  _NEULANDHIT_VECTOR3D._serialized_start=229
  _NEULANDHIT_VECTOR3D._serialized_end=272
  _NEULANDHITS._serialized_start=274
  _NEULANDHITS._serialized_end=323
# @@protoc_insertion_point(module_scope)
